# Generated by Django 3.1 on 2020-08-29 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='task',
            name='finished_date',
            field=models.DateTimeField(null=True),
        ),
    ]
