# Generated by Django 3.1 on 2020-09-02 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20200829_2046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='finished_date',
            new_name='concluded_date',
        ),
    ]
